id: finally-failure-flow
namespace: company.team

tasks:
  - id: log
    type: io.kestra.plugin.core.execution.Fail

finally:
  - id: final_task
    type: io.kestra.plugin.core.log.Log
    message: "This task gets executed irrespective of whether the flow is successful or failed."

extend:
  title: Using finally to run the task at the end of the failed flow
  description: >-
    This flow demonstrates that the tasks in the `finally` block gets executed even when the 
    flow has failed.
  tags:
    - Software Engineering
  ee: false
  demo: false
  meta_description: This flow demonstrated finally task for failed flow.
