id: retries
namespace: sanitychecks
tasks:
  - id: fail_4_times
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - if [ "{{ taskrun.attemptsCount }}" -eq 4 ]; then exit 0; else exit 1; fi
    retry:
      type: constant
      interval: PT0.25S
      maxAttempt: 5
      maxDuration: PT1M
      warningOnRetry: false
errors:
  - id: will_never_happen
    type: io.kestra.plugin.core.debug.Return
    format: This will never be executed as retries will fix the issue
